spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: randima@94
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create

server:
  port: 8181

jwt:
  secret: javainuse
