spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookDB?createDatabaseIfNotExist=true
    username: root
    password: randima@94
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  servlet:
    multipart:
      enabled : true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB