spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/apiGatewayDB?createDatabaseIfNotExist=true
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.8.103:8761/eureka/

zuul:
  routes:
    book:
      path: /book/**
      url: book
    transaction:
      path: /transaction/**
      url: transaction
    user:
      path: /user/**
      url: user

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

jwt:
  secret: javainuse
